spring:
  sql:
    init:
      mode: always
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: jypark
    password: ${SPRING_DATASOURCE_PASSWORD}
