spring:
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: jypark
    password: ${SPRING_DATASOURCE_PASSWORD}
logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  issuer: jypark-anycommerce-backend
  secret_key: ${JWT_SECRET_KEY}
